### ISSUE TITLE
这个是不是缺一个排序啊？

### ISSUE THREAD

**Issue by naix1024** [zhangxiang0316/vueUtils#1]
比如说第一次表单的顺序是单行文本、富文本
然后我拖拽调整一下顺序成了富文本，然后是单行文本

最后运行渲染的时候，还是按照第一次的顺序

**Comment by zhangxiang0316** [comment]
你描述的情况没有发现，能否截图看一下

**Comment by zhangxiang0316** [comment]
> 第一次文本格式形成的顺序是先行文本、富文本 然后我拖单拖整理富文本，然后是行文本
> 
> 运行渲染的时候，最后还是按照第一次的顺序

你的情况没有发现，可以截图描述看一下

**Comment by zhangxiang0316** [comment]
> 第一次文本格式的顺序是先行文本、富文本 然后我拖拽整理形成富文本，然后是单行文本
> 
> 运行渲染的时候，最后还是按照第一次的顺序

请去  分组拖拽  查看

**Comment by naix1024** [comment]
哦哦    看到了，分组拖拽没有这个顺序的问题。但是分组拖拽的导出json，导出的内容不全

**Comment by zhangxiang0316** [comment]
> 



> 哦哦哦哦看到了，拖拖拉拉没有这个顺序的。但是拖着拖拽的导出json，导出的内容不全

这个项目是之前练手用的，现在很少维护了，有什么问题一块交流

**Comment by zhangxiang0316** [comment]
> 

这个项目是之前练手用的，现在很少维护了，有啥问题我们讨论下

**Comment by naix1024** [comment]
> > 
> 
> 这个项目是之前练手用的，现在很少维护了，有啥问题我们讨论下

恩恩，最近在看拖拉拽表单的实现，一点点找到你这个项目。
表单是不包括表格的是吧，如果拖拽表格，填写一部分，空着一部分，对这个你有什么实现思路吗？

**Comment by zhangxiang0316** [comment]
> > > 
> > 
> > 
> > 这个项目是之前练手用的，现在很少维护了，有啥问题我们讨论下
> 
> 恩恩，最近在看拖拉拽表单的实现，一点点找到你这个项目。 表单是不包括表格的是吧，如果拖拽表格，填写一部分，空着一部分，对这个你有什么实现思路吗？

你更新一下，我添加了一下table，不过属性我只添加了tableCols 的设置，你可以更新下自己添加其他设置，弄成动态的就行了
